### PR TITLE
fix PcpMmvWriter race condition

### LINKED ISSUE #132: Race condition causes metric updates to be lost
If a metric is updated while `QuiescentRegistryListener` is restarting `PcpMmvWriter` due to a monitorable being added, then it's possible that the metric update will be lost. This can happen because the metric update calls `PcpMmvWriter.updateMetric()`, which immediately returns if `started` is `false`. When `QuiescentRegistryListener` restarts `PcpMmvWriter`, it first stops it, setting `started` to `false`, and then starts it again. `PcpMmvWriter.start()` iterates over all of the metric data, writing it again, prior to setting `started` to `true`. So, the race occurs if a metric is updated between the time the old value is rewritten in `PcpMmvWriter.start()` and the time `started` is set to `true`.

### PR DESCRIPTION
**Pull request by pwinckles**
Fixes a race condition where metric updates can be lost if the happen while `PcpMmvWriter` is being reset. Previously, updates were dropped if the writer was not in a started state. If this happened while the the writer was executing `start()`, then it's possible the updated value would be lost if the old metric value had already been written.

The issue is addressed here by blocking the metric update when the writer is in a `STARTING` state, until the writer has been fully started. If the writer is in a `STARTED` state, the update is applied immediately. If the writer is in a `STOPPED` state, the update is dropped immediately.

Resolves #132

### CODE REVIEW

File: dxm/src/main/java/io/pcp/parfait/dxm/PcpMmvWriter.java [hunk 1]
```diff
@@ -307,9 +317,22 @@ public final <T> void registerType(Class<T> runtimeClass, TypeHandler<T> handler
...
-        if (!started) {
-            return;
+        // If another thread has called start() we need to wait until the writer has completely started before
+        // proceeding to update the metric value. This is to avoid a race condition where start() has already written
+        // the old metric value, but has not yet finished writing all of the values, when the metric is updated. The
+        // implementation here is a little complicated to avoid taking a lock on the happy paths.
+        if (state == State.STARTED) {
+            doUpdateMetric(name, value);
+        } else if (state == State.STARTING) {
+            if (stateMonitor.enterWhenUninterruptibly(isStarted, Duration.ofSeconds(10))) {
```
Comment (tallpsmith) [inline dxm/src/main/java/io/pcp/parfait/dxm/PcpMmvWriter.java:327]: I'm just channeling some things we observed during my Aconex days, where any of the synchronization overhead for metric updates caused grief. Particularly during startup with lots of metrics (this is why the QuiescentRegistryListener is there, just to help soften the blow of so many new metrics turning up during startup.)

Can we make the block wait time configurable rather than hard-coded? (leave the user to control how much they value this data loss over synchronization overhead?)

I presume with this tricky concurrency, no easy path to automate some unit tests here? (Man I hate doing that too, just asking...)

Comment (pwinckles) [reply dxm/src/main/java/io/pcp/parfait/dxm/PcpMmvWriter.java:327]: @tallpsmith Would you like me to add the configuration to `MonitoringViewProperties`? Do you think 10 seconds is a reasonable default? Note that the duration is the maximum time it will wait. I would be surprised if it ever actually waited that long.

Reliable, cross-system concurrency testing is a can of worms. I can see if I can get anything to work tomorrow.

Comment (pwinckles) [reply dxm/src/main/java/io/pcp/parfait/dxm/PcpMmvWriter.java:327]: @tallpsmith Just added a test that I think should be reliable. I confirmed it fails on the old code.

Comment (pwinckles) [reply dxm/src/main/java/io/pcp/parfait/dxm/PcpMmvWriter.java]: @tallpsmith Just pushed another commit that makes the wait time configurable. Let me know if it's what you had in mind, and, if so, if you'd also like `parfait.sh` updated.

Comment (tallpsmith) [reply dxm/src/main/java/io/pcp/parfait/dxm/PcpMmvWriter.java]: I don't know much about `parfait.sh` (@natoscott  ?) - but I _think_ it's not necessary (or we can do it in another release if it's important enough).
